DO $$ BEGIN CREATE TYPE public.account_type AS ENUM ('persona_fisica', 'persona_moral'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.app_role AS ENUM ('buyer', 'seller', 'admin', 'verifier', 'mediator'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.clabe_nivel AS ENUM ('algoritmica', 'penny_test', 'documental'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.clabe_status AS ENUM ('pending', 'verifying', 'verified', 'failed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.commission_payer AS ENUM ('buyer', 'seller', 'split'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.condition_status AS ENUM ('pending', 'met', 'rejected'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.incident_severity AS ENUM ('minor', 'major', 'critical'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.incident_status AS ENUM ('investigating', 'identified', 'monitoring', 'resolved'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.industry_sector AS ENUM ('autotransporte', 'construccion', 'inmobiliario', 'vehiculos', 'servicios_profesionales', 'comercio', 'manufactura', 'otro'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.internal_role AS ENUM ('YOKTO_SUPER_ADMIN', 'ANALISTA_KYC', 'ANALISTA_DOCUMENTAL', 'OFICIAL_CUMPLIMIENTO', 'AGENTE_ESCROW', 'AGENTE_SOPORTE', 'ANALISTA_FINANCIERO'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.kyb_status AS ENUM ('not_started', 'in_review', 'approved', 'rejected'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.kyc_document_type AS ENUM ('ine', 'passport', 'proof_of_address', 'acta_constitutiva', 'constancia_fiscal', 'poder_notarial', 'other', 'ine_frente', 'ine_reverso', 'selfie_con_id', 'cedula_fiscal'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.kyc_nivel AS ENUM ('basico', 'intermedio', 'avanzado'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.kyc_status AS ENUM ('pending', 'in_review', 'approved', 'rejected'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.membership_status AS ENUM ('active', 'invited', 'suspended', 'removed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.org_plan AS ENUM ('free', 'pro', 'enterprise'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.org_role AS ENUM ('owner', 'buyer_admin', 'buyer_user', 'seller_admin', 'seller_user', 'auditor'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.org_type AS ENUM ('individual', 'business'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.payment_method AS ENUM ('spei', 'card'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.platform_role AS ENUM ('compliance', 'dispute_manager', 'support', 'platform_admin'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.pld_alert_severity AS ENUM ('info', 'baja', 'media', 'alta', 'critica'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.pld_alert_status AS ENUM ('abierta', 'en_revision', 'resuelta', 'descartada', 'escalada'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.pld_profile_status AS ENUM ('borrador', 'vigente', 'en_revision', 'vencido', 'bloqueado'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.pld_risk_level AS ENUM ('bajo', 'medio', 'alto', 'inaceptable'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.pld_screening_list AS ENUM ('pep_nacional', 'pep_internacional', 'ofac', 'onu', 'ue', 'adverse_media', 'interpol', 'sat_69b'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.pld_screening_status AS ENUM ('limpio', 'coincidencia_debil', 'coincidencia_fuerte', 'error'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.support_escalation_type AS ENUM ('none', 'conflict', 'pld_ft', 'financial', 'technical'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.support_ticket_priority AS ENUM ('low', 'normal', 'high', 'urgent'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.support_ticket_status AS ENUM ('open', 'pending_user', 'in_progress', 'escalated', 'resolved', 'closed', 'reopened'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.transaction_status AS ENUM ('draft', 'awaiting_funding', 'funded', 'in_progress', 'conditions_met', 'released', 'disputed', 'cancelled', 'refunded', 'pending_signature', 'partial_release', 'en_verificacion'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
