CREATE UNIQUE INDEX api_clients_key_id_key ON public.api_clients USING btree (key_id);
CREATE INDEX idx_audit_entity ON public.audit_events USING btree (entity_type, entity_id);
CREATE INDEX idx_audit_org_created ON public.audit_events USING btree (org_id, created_at DESC);
CREATE INDEX audit_log_entity_idx ON public.audit_log USING btree (entity_type, entity_id);
CREATE INDEX audit_log_user_idx ON public.audit_log USING btree (user_id);
CREATE UNIQUE INDEX bank_account_penny_tests_provider_uuid_key ON public.bank_account_penny_tests USING btree (provider_uuid);
CREATE INDEX idx_penny_tests_bank_account ON public.bank_account_penny_tests USING btree (bank_account_id);
CREATE INDEX idx_penny_tests_status ON public.bank_account_penny_tests USING btree (status);
CREATE INDEX idx_bank_accounts_org ON public.bank_accounts USING btree (owner_org_id);
CREATE INDEX idx_bank_accounts_status ON public.bank_accounts USING btree (verification_status);
CREATE UNIQUE INDEX idx_bank_accounts_unique_hash_org ON public.bank_accounts USING btree (owner_org_id, query_hash) WHERE ((owner_org_id IS NOT NULL) AND (archived_at IS NULL));
CREATE UNIQUE INDEX idx_bank_accounts_unique_hash_user ON public.bank_accounts USING btree (owner_user_id, query_hash) WHERE ((owner_user_id IS NOT NULL) AND (archived_at IS NULL));
CREATE INDEX idx_bank_accounts_user ON public.bank_accounts USING btree (owner_user_id);
CREATE INDEX ix_biometric_api_logs_enrollment ON public.biometric_api_logs USING btree (enrollment_id, created_at DESC);
CREATE UNIQUE INDEX biometric_enrollments_token_key ON public.biometric_enrollments USING btree (token);
CREATE INDEX ix_biometric_enrollments_token ON public.biometric_enrollments USING btree (token);
CREATE INDEX ix_biometric_enrollments_user ON public.biometric_enrollments USING btree (user_id, created_at DESC);
CREATE INDEX clabe_verifications_user_idx ON public.clabe_verifications USING btree (user_id);
CREATE UNIQUE INDEX connected_accounts_user_id_key ON public.connected_accounts USING btree (user_id);
CREATE INDEX contract_signatures_contract_idx ON public.contract_signatures USING btree (contract_id);
CREATE INDEX contract_signatures_tx_idx ON public.contract_signatures USING btree (transaction_id);
CREATE INDEX idx_curp_verifications_curp ON public.curp_verifications USING btree (curp);
CREATE INDEX idx_curp_verifications_user ON public.curp_verifications USING btree (user_id);
CREATE INDEX dispute_evidence_dispute_idx ON public.dispute_evidence USING btree (dispute_id);
CREATE INDEX dispute_messages_dispute_idx ON public.dispute_messages USING btree (dispute_id);
CREATE UNIQUE INDEX disputes_numero_key ON public.disputes USING btree (numero) WHERE (numero IS NOT NULL);
CREATE INDEX disputes_status_idx ON public.disputes USING btree (status);
CREATE UNIQUE INDEX disputes_transaction_id_key ON public.disputes USING btree (transaction_id);
CREATE INDEX disputes_tx_idx ON public.disputes USING btree (transaction_id);
CREATE INDEX idx_docrev_pending ON public.document_review_queue USING btree (estado, prioridad, created_at) WHERE (estado = ANY (ARRAY['PENDIENTE'::text, 'EN_REVISION'::text]));
CREATE INDEX idx_docrev_tx ON public.document_review_queue USING btree (transaction_id);
CREATE UNIQUE INDEX fiscal_documents_uuid_fiscal_key ON public.fiscal_documents USING btree (uuid_fiscal);
CREATE INDEX idx_fiscal_docs_estado ON public.fiscal_documents USING btree (estado);
CREATE INDEX idx_fiscal_docs_hito ON public.fiscal_documents USING btree (hito_id);
CREATE INDEX idx_fiscal_docs_parent ON public.fiscal_documents USING btree (parent_cfdi_id);
CREATE INDEX idx_fiscal_docs_tx ON public.fiscal_documents USING btree (transaction_id);
CREATE INDEX idx_fiscal_docs_uuid ON public.fiscal_documents USING btree (uuid_fiscal);
CREATE INDEX help_articles_search_idx ON public.help_articles USING gin (to_tsvector('spanish'::regconfig, ((((COALESCE(title, ''::text) || ' '::text) || COALESCE(summary, ''::text)) || ' '::text) || COALESCE(body_md, ''::text))));
CREATE UNIQUE INDEX help_articles_slug_key ON public.help_articles USING btree (slug);
CREATE UNIQUE INDEX help_categories_slug_key ON public.help_categories USING btree (slug);
CREATE INDEX idx_iact_entity ON public.internal_action_log USING btree (entidad_tipo, entidad_id);
CREATE INDEX idx_iact_user ON public.internal_action_log USING btree (user_id, created_at DESC);
CREATE UNIQUE INDEX idx_internal_role_user_active ON public.internal_role_assignments USING btree (user_id) WHERE (activo = true);
CREATE INDEX idx_invitations_email ON public.invitations USING btree (lower(email));
CREATE INDEX idx_invitations_org ON public.invitations USING btree (org_id);
CREATE UNIQUE INDEX invitations_token_key ON public.invitations USING btree (token);
CREATE INDEX idx_memberships_user ON public.memberships USING btree (user_id);
CREATE INDEX notifications_user_idx ON public.notifications USING btree (user_id, read_at, created_at DESC);
CREATE UNIQUE INDEX organizations_slug_key ON public.organizations USING btree (slug);
CREATE INDEX payment_intents_tx_idx ON public.payment_intents USING btree (transaction_id);
CREATE INDEX payouts_tx_idx ON public.payouts USING btree (transaction_id);
CREATE UNIQUE INDEX platform_roles_user_id_role_key ON public.platform_roles USING btree (user_id, role);
CREATE INDEX pld_alerts_org_idx ON public.pld_alerts USING btree (org_id, detected_at DESC);
CREATE INDEX pld_alerts_status_idx ON public.pld_alerts USING btree (status) WHERE (status = ANY (ARRAY['abierta'::pld_alert_status, 'en_revision'::pld_alert_status, 'escalada'::pld_alert_status]));
CREATE UNIQUE INDEX pld_questionnaires_org_id_version_key ON public.pld_questionnaires USING btree (org_id, version);
CREATE INDEX pld_questionnaires_org_idx ON public.pld_questionnaires USING btree (org_id);
CREATE INDEX pld_risk_factors_org_idx ON public.pld_risk_factors USING btree (org_id, evaluated_at DESC);
CREATE UNIQUE INDEX pld_risk_profiles_org_id_key ON public.pld_risk_profiles USING btree (org_id);
CREATE INDEX pld_screening_org_idx ON public.pld_screening_results USING btree (org_id, evaluated_at DESC);
CREATE INDEX idx_postal_code_lookups_cp ON public.postal_code_lookups USING btree (cp);
CREATE INDEX idx_postal_code_lookups_user_id ON public.postal_code_lookups USING btree (user_id);
CREATE UNIQUE INDEX profiles_curp_key ON public.profiles USING btree (curp);
CREATE INDEX idx_stripe_webhook_events_event_id ON public.stripe_webhook_events USING btree (event_id);
CREATE INDEX idx_stripe_webhook_events_processed ON public.stripe_webhook_events USING btree (processed) WHERE (processed = false);
CREATE UNIQUE INDEX stripe_webhook_events_event_id_key ON public.stripe_webhook_events USING btree (event_id);
CREATE INDEX idx_sad_ticket ON public.support_attachment_downloads USING btree (ticket_id, created_at DESC);
CREATE INDEX idx_support_tickets_esc_notify ON public.support_tickets USING btree (escalated_at) WHERE ((escalation_notified_at IS NULL) AND (escalation <> 'none'::support_escalation_type));
CREATE INDEX idx_support_tickets_live_chat ON public.support_tickets USING btree (user_id, is_live_chat, status) WHERE (is_live_chat = true);
CREATE INDEX idx_support_tickets_sla_warn ON public.support_tickets USING btree (sla_first_response_at) WHERE ((first_response_at IS NULL) AND (sla_warn_notified_at IS NULL) AND (status <> 'closed'::support_ticket_status));
CREATE UNIQUE INDEX support_tickets_numero_key ON public.support_tickets USING btree (numero);
CREATE INDEX idx_cond_tx ON public.transaction_conditions USING btree (transaction_id);
CREATE INDEX transaction_contracts_tx_idx ON public.transaction_contracts USING btree (transaction_id);
CREATE INDEX idx_tx_documents_tx ON public.transaction_documents USING btree (transaction_id);
CREATE INDEX idx_tx_documents_type ON public.transaction_documents USING btree (doc_type);
CREATE INDEX idx_evt_tx ON public.transaction_events USING btree (transaction_id);
CREATE INDEX idx_hitos_estado ON public.transaction_hitos USING btree (estado);
CREATE INDEX idx_hitos_tx ON public.transaction_hitos USING btree (transaction_id);
CREATE UNIQUE INDEX transaction_hitos_transaction_id_orden_key ON public.transaction_hitos USING btree (transaction_id, orden);
CREATE INDEX idx_tx_buyer ON public.transactions USING btree (buyer_id);
CREATE INDEX idx_tx_seller ON public.transactions USING btree (seller_id);
CREATE INDEX idx_tx_status ON public.transactions USING btree (status);
CREATE UNIQUE INDEX transactions_numero_key ON public.transactions USING btree (numero);
CREATE UNIQUE INDEX user_roles_user_id_role_key ON public.user_roles USING btree (user_id, role);
