ALTER TABLE public.api_clients ADD CONSTRAINT api_clients_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.audit_events ADD CONSTRAINT audit_events_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.audit_events ADD CONSTRAINT audit_events_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
ALTER TABLE public.audit_log ADD CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.bank_account_penny_tests ADD CONSTRAINT bank_account_penny_tests_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES bank_accounts(id) ON DELETE CASCADE;
ALTER TABLE public.bank_account_penny_tests ADD CONSTRAINT bank_account_penny_tests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
ALTER TABLE public.bank_accounts ADD CONSTRAINT bank_accounts_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.bank_accounts ADD CONSTRAINT bank_accounts_owner_org_id_fkey FOREIGN KEY (owner_org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.bank_accounts ADD CONSTRAINT bank_accounts_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.bank_accounts ADD CONSTRAINT bank_accounts_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id);
ALTER TABLE public.biometric_api_logs ADD CONSTRAINT biometric_api_logs_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES biometric_enrollments(id) ON DELETE CASCADE;
ALTER TABLE public.biometric_api_logs ADD CONSTRAINT biometric_api_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.biometric_enrollments ADD CONSTRAINT biometric_enrollments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.clabe_verifications ADD CONSTRAINT clabe_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.connected_accounts ADD CONSTRAINT connected_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.contract_signatures ADD CONSTRAINT contract_signatures_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES transaction_contracts(id) ON DELETE CASCADE;
ALTER TABLE public.contract_signatures ADD CONSTRAINT contract_signatures_signer_user_id_fkey FOREIGN KEY (signer_user_id) REFERENCES auth.users(id);
ALTER TABLE public.contract_signatures ADD CONSTRAINT contract_signatures_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE;
ALTER TABLE public.curp_verifications ADD CONSTRAINT curp_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.dispute_evidence ADD CONSTRAINT dispute_evidence_dispute_id_fkey FOREIGN KEY (dispute_id) REFERENCES disputes(id) ON DELETE CASCADE;
ALTER TABLE public.dispute_evidence ADD CONSTRAINT dispute_evidence_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.dispute_messages ADD CONSTRAINT dispute_messages_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.dispute_messages ADD CONSTRAINT dispute_messages_dispute_id_fkey FOREIGN KEY (dispute_id) REFERENCES disputes(id) ON DELETE CASCADE;
ALTER TABLE public.disputes ADD CONSTRAINT disputes_hito_id_fkey FOREIGN KEY (hito_id) REFERENCES transaction_hitos(id) ON DELETE SET NULL;
ALTER TABLE public.disputes ADD CONSTRAINT disputes_mediator_id_fkey FOREIGN KEY (mediator_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.disputes ADD CONSTRAINT disputes_opened_by_fkey FOREIGN KEY (opened_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.disputes ADD CONSTRAINT disputes_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE;
ALTER TABLE public.document_review_queue ADD CONSTRAINT document_review_queue_asignado_a_fkey FOREIGN KEY (asignado_a) REFERENCES auth.users(id);
ALTER TABLE public.document_review_queue ADD CONSTRAINT document_review_queue_revisado_por_fkey FOREIGN KEY (revisado_por) REFERENCES auth.users(id);
ALTER TABLE public.document_review_queue ADD CONSTRAINT document_review_queue_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE;
ALTER TABLE public.fiscal_documents ADD CONSTRAINT fiscal_documents_aceptado_por_fkey FOREIGN KEY (aceptado_por) REFERENCES auth.users(id);
ALTER TABLE public.fiscal_documents ADD CONSTRAINT fiscal_documents_hito_id_fkey FOREIGN KEY (hito_id) REFERENCES transaction_hitos(id) ON DELETE SET NULL;
ALTER TABLE public.fiscal_documents ADD CONSTRAINT fiscal_documents_parent_cfdi_id_fkey FOREIGN KEY (parent_cfdi_id) REFERENCES fiscal_documents(id) ON DELETE SET NULL;
ALTER TABLE public.fiscal_documents ADD CONSTRAINT fiscal_documents_rechazado_por_fkey FOREIGN KEY (rechazado_por) REFERENCES auth.users(id);
ALTER TABLE public.fiscal_documents ADD CONSTRAINT fiscal_documents_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE;
ALTER TABLE public.fiscal_documents ADD CONSTRAINT fiscal_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id);
ALTER TABLE public.help_articles ADD CONSTRAINT help_articles_category_id_fkey FOREIGN KEY (category_id) REFERENCES help_categories(id) ON DELETE SET NULL;
ALTER TABLE public.internal_access_log ADD CONSTRAINT internal_access_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
ALTER TABLE public.internal_action_log ADD CONSTRAINT internal_action_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
ALTER TABLE public.internal_role_assignments ADD CONSTRAINT internal_role_assignments_asignado_por_fkey FOREIGN KEY (asignado_por) REFERENCES auth.users(id);
ALTER TABLE public.internal_role_assignments ADD CONSTRAINT internal_role_assignments_revocado_por_fkey FOREIGN KEY (revocado_por) REFERENCES auth.users(id);
ALTER TABLE public.internal_role_assignments ADD CONSTRAINT internal_role_assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.invitations ADD CONSTRAINT invitations_accepted_by_fkey FOREIGN KEY (accepted_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.invitations ADD CONSTRAINT invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.invitations ADD CONSTRAINT invitations_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.kyc_documents ADD CONSTRAINT kyc_documents_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id);
ALTER TABLE public.kyc_documents ADD CONSTRAINT kyc_documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.memberships ADD CONSTRAINT memberships_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.memberships ADD CONSTRAINT memberships_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.memberships ADD CONSTRAINT memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.organizations ADD CONSTRAINT organizations_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.payment_intents ADD CONSTRAINT payment_intents_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE;
ALTER TABLE public.payouts ADD CONSTRAINT payouts_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.payouts ADD CONSTRAINT payouts_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE;
ALTER TABLE public.platform_roles ADD CONSTRAINT platform_roles_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.platform_roles ADD CONSTRAINT platform_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.pld_alerts ADD CONSTRAINT pld_alerts_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.pld_alerts ADD CONSTRAINT pld_alerts_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id);
ALTER TABLE public.pld_alerts ADD CONSTRAINT pld_alerts_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE SET NULL;
ALTER TABLE public.pld_questionnaires ADD CONSTRAINT pld_questionnaires_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.pld_questionnaires ADD CONSTRAINT pld_questionnaires_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.pld_risk_factors ADD CONSTRAINT pld_risk_factors_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.pld_risk_factors ADD CONSTRAINT pld_risk_factors_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES pld_risk_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.pld_risk_profiles ADD CONSTRAINT pld_risk_profiles_evaluated_by_fkey FOREIGN KEY (evaluated_by) REFERENCES auth.users(id);
ALTER TABLE public.pld_risk_profiles ADD CONSTRAINT pld_risk_profiles_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.pld_screening_results ADD CONSTRAINT pld_screening_results_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.postal_code_lookups ADD CONSTRAINT postal_code_lookups_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.reports_ledger ADD CONSTRAINT reports_ledger_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.reports_ledger ADD CONSTRAINT reports_ledger_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE SET NULL;
ALTER TABLE public.support_attachment_downloads ADD CONSTRAINT support_attachment_downloads_attachment_id_fkey FOREIGN KEY (attachment_id) REFERENCES support_attachments(id) ON DELETE CASCADE;
ALTER TABLE public.support_attachment_downloads ADD CONSTRAINT support_attachment_downloads_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES support_tickets(id) ON DELETE CASCADE;
ALTER TABLE public.support_attachment_downloads ADD CONSTRAINT support_attachment_downloads_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.support_attachments ADD CONSTRAINT support_attachments_message_id_fkey FOREIGN KEY (message_id) REFERENCES support_messages(id) ON DELETE SET NULL;
ALTER TABLE public.support_attachments ADD CONSTRAINT support_attachments_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES support_tickets(id) ON DELETE CASCADE;
ALTER TABLE public.support_attachments ADD CONSTRAINT support_attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.support_messages ADD CONSTRAINT support_messages_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.support_messages ADD CONSTRAINT support_messages_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES support_tickets(id) ON DELETE CASCADE;
ALTER TABLE public.support_tickets ADD CONSTRAINT support_tickets_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
ALTER TABLE public.support_tickets ADD CONSTRAINT support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.transaction_conditions ADD CONSTRAINT transaction_conditions_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE;
ALTER TABLE public.transaction_conditions ADD CONSTRAINT transaction_conditions_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES auth.users(id);
ALTER TABLE public.transaction_contracts ADD CONSTRAINT transaction_contracts_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.transaction_contracts ADD CONSTRAINT transaction_contracts_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE;
ALTER TABLE public.transaction_documents ADD CONSTRAINT transaction_documents_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE;
ALTER TABLE public.transaction_documents ADD CONSTRAINT transaction_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.transaction_events ADD CONSTRAINT transaction_events_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES auth.users(id);
ALTER TABLE public.transaction_events ADD CONSTRAINT transaction_events_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE;
ALTER TABLE public.transaction_hitos ADD CONSTRAINT transaction_hitos_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE;
ALTER TABLE public.transactions ADD CONSTRAINT transactions_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES auth.users(id) ON DELETE RESTRICT;
ALTER TABLE public.transactions ADD CONSTRAINT transactions_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.transactions ADD CONSTRAINT transactions_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES auth.users(id) ON DELETE RESTRICT;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.verification_evidence ADD CONSTRAINT verification_evidence_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE;
ALTER TABLE public.verification_evidence ADD CONSTRAINT verification_evidence_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id) ON DELETE CASCADE;
