ALTER TABLE public.api_clients ADD CONSTRAINT api_clients_key_id_key UNIQUE (key_id);
ALTER TABLE public.bank_account_penny_tests ADD CONSTRAINT bank_account_penny_tests_provider_uuid_key UNIQUE (provider_uuid);
ALTER TABLE public.bank_account_penny_tests ADD CONSTRAINT bank_account_penny_tests_rfc_curp_match_check CHECK ((rfc_curp_match = ANY (ARRAY['EXACT'::text, 'PARTIAL'::text, 'NO_MATCH'::text, 'MISSING'::text])));
ALTER TABLE public.bank_account_penny_tests ADD CONSTRAINT bank_account_penny_tests_status_check CHECK ((status = ANY (ARRAY['PENNY_CREATED'::text, 'WAITING_RESULT'::text, 'APPROVED'::text, 'MANUAL_REVIEW'::text, 'REJECTED'::text, 'ERROR'::text, 'EXPIRED'::text])));
ALTER TABLE public.bank_account_penny_tests ADD CONSTRAINT bank_account_penny_tests_type_check CHECK ((type = ANY (ARRAY['CLABE'::text, 'DEBIT_CARD'::text])));
ALTER TABLE public.bank_accounts ADD CONSTRAINT bank_accounts_account_type_check CHECK ((account_type = ANY (ARRAY['CLABE'::text, 'DEBIT_CARD'::text])));
ALTER TABLE public.bank_accounts ADD CONSTRAINT bank_accounts_check CHECK (((owner_user_id IS NOT NULL) OR (owner_org_id IS NOT NULL)));
ALTER TABLE public.bank_accounts ADD CONSTRAINT bank_accounts_verification_status_check CHECK ((verification_status = ANY (ARRAY['DRAFT'::text, 'LOCAL_VALIDATED'::text, 'PENNY_CREATED'::text, 'WAITING_RESULT'::text, 'APPROVED'::text, 'MANUAL_REVIEW'::text, 'REJECTED'::text, 'ERROR'::text, 'EXPIRED'::text])));
ALTER TABLE public.biometric_enrollments ADD CONSTRAINT biometric_enrollments_id_type_check CHECK ((id_type = ANY (ARRAY['ine'::text, 'passport'::text])));
ALTER TABLE public.biometric_enrollments ADD CONSTRAINT biometric_enrollments_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'id_captured'::text, 'id_verified'::text, 'face_verified'::text, 'address_verified'::text, 'completed'::text, 'failed'::text, 'expired'::text])));
ALTER TABLE public.biometric_enrollments ADD CONSTRAINT biometric_enrollments_token_key UNIQUE (token);
ALTER TABLE public.connected_accounts ADD CONSTRAINT connected_accounts_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'onboarding'::text, 'verified'::text, 'restricted'::text, 'disabled'::text])));
ALTER TABLE public.connected_accounts ADD CONSTRAINT connected_accounts_user_id_key UNIQUE (user_id);
ALTER TABLE public.contract_signatures ADD CONSTRAINT contract_signatures_method_check CHECK ((method = ANY (ARRAY['AUTOGRAFA_BIOMETRICA'::text, 'EFIRMA_SAT'::text])));
ALTER TABLE public.contract_signatures ADD CONSTRAINT contract_signatures_signer_role_check CHECK ((signer_role = ANY (ARRAY['PAGADOR'::text, 'BENEFICIARIO'::text, 'REPRESENTANTE_LEGAL'::text, 'TESTIGO'::text, 'ADMIN_YOKTO'::text])));
ALTER TABLE public.contract_signatures ADD CONSTRAINT contract_signatures_status_check CHECK ((status = ANY (ARRAY['PENDING'::text, 'SIGNED'::text, 'FAILED'::text, 'REJECTED'::text, 'EXPIRED'::text, 'MANUAL_REVIEW'::text])));
ALTER TABLE public.dispute_evidence ADD CONSTRAINT dispute_evidence_kind_check CHECK ((kind = ANY (ARRAY['photo'::text, 'video'::text, 'document'::text, 'screenshot'::text, 'other'::text])));
ALTER TABLE public.dispute_evidence ADD CONSTRAINT dispute_evidence_uploader_role_check CHECK ((uploader_role = ANY (ARRAY['buyer'::text, 'seller'::text, 'mediator'::text, 'admin'::text])));
ALTER TABLE public.dispute_messages ADD CONSTRAINT dispute_messages_author_role_check CHECK ((author_role = ANY (ARRAY['buyer'::text, 'seller'::text, 'mediator'::text, 'admin'::text, 'system'::text])));
ALTER TABLE public.dispute_messages ADD CONSTRAINT dispute_messages_message_type_check CHECK ((message_type = ANY (ARRAY['text'::text, 'system'::text, 'resolution'::text, 'mediation'::text])));
ALTER TABLE public.dispute_messages ADD CONSTRAINT dispute_messages_visible_to_check CHECK ((visible_to = ANY (ARRAY['all'::text, 'mediator_only'::text, 'buyer_and_mediator'::text, 'seller_and_mediator'::text])));
ALTER TABLE public.disputes ADD CONSTRAINT disputes_deposit_returned_to_check CHECK (((deposit_returned_to IS NULL) OR (deposit_returned_to = ANY (ARRAY['buyer'::text, 'seller'::text, 'split'::text, 'yokto'::text]))));
ALTER TABLE public.disputes ADD CONSTRAINT disputes_loser_pays_check CHECK ((loser_pays = ANY (ARRAY['buyer'::text, 'seller'::text, 'split'::text, 'none'::text])));
ALTER TABLE public.disputes ADD CONSTRAINT disputes_opened_role_check CHECK ((opened_role = ANY (ARRAY['buyer'::text, 'seller'::text])));
ALTER TABLE public.disputes ADD CONSTRAINT disputes_percent_release_seller_check CHECK (((percent_release_seller IS NULL) OR ((percent_release_seller >= (0)::numeric) AND (percent_release_seller <= (100)::numeric))));
ALTER TABLE public.disputes ADD CONSTRAINT disputes_reason_code_check CHECK ((reason_code = ANY (ARRAY['incumplimiento_hito'::text, 'documentos_invalidos'::text, 'mercancia_incompleta'::text, 'calidad_insuficiente'::text, 'plazo_vencido'::text, 'fraude_sospechado'::text, 'condiciones_no_acordadas'::text, 'otro'::text, 'not_delivered'::text, 'not_as_described'::text, 'quality'::text, 'delay'::text, 'fraud'::text, 'other'::text])));
ALTER TABLE public.disputes ADD CONSTRAINT disputes_resolution_check CHECK ((resolution = ANY (ARRAY['buyer_favor'::text, 'seller_favor'::text, 'split'::text, 'no_resolution'::text])));
ALTER TABLE public.disputes ADD CONSTRAINT disputes_status_check CHECK ((status = ANY (ARRAY['pending_deposit'::text, 'open'::text, 'awaiting_response'::text, 'in_review'::text, 'in_mediation'::text, 'resolved'::text, 'escalated'::text, 'withdrawn'::text, 'closed'::text, 'cancelled'::text])));
ALTER TABLE public.disputes ADD CONSTRAINT disputes_transaction_id_key UNIQUE (transaction_id);
ALTER TABLE public.document_review_queue ADD CONSTRAINT document_review_queue_confianza_ia_check CHECK (((confianza_ia >= 0) AND (confianza_ia <= 100)));
ALTER TABLE public.document_review_queue ADD CONSTRAINT document_review_queue_estado_check CHECK ((estado = ANY (ARRAY['PENDIENTE'::text, 'EN_REVISION'::text, 'VALIDADO'::text, 'RECHAZADO'::text, 'CORRECCION_SOLICITADA'::text, 'ESCALADO'::text, 'INCONCLUSO'::text])));
ALTER TABLE public.document_review_queue ADD CONSTRAINT document_review_queue_prioridad_check CHECK ((prioridad = ANY (ARRAY['BAJA'::text, 'NORMAL'::text, 'ALTA'::text, 'CRITICA'::text])));
ALTER TABLE public.fiscal_documents ADD CONSTRAINT fiscal_documents_estado_check CHECK ((estado = ANY (ARRAY['SUBIDO'::text, 'VALIDANDO'::text, 'VALIDADO'::text, 'ACEPTADO'::text, 'RECHAZADO'::text, 'CANCELADO_SAT'::text])));
ALTER TABLE public.fiscal_documents ADD CONSTRAINT fiscal_documents_tipo_check CHECK ((tipo = ANY (ARRAY['CFDI_PPD'::text, 'CFDI_PUE'::text, 'REP'::text])));
ALTER TABLE public.fiscal_documents ADD CONSTRAINT fiscal_documents_uuid_fiscal_key UNIQUE (uuid_fiscal);
ALTER TABLE public.help_articles ADD CONSTRAINT help_articles_slug_key UNIQUE (slug);
ALTER TABLE public.help_categories ADD CONSTRAINT help_categories_slug_key UNIQUE (slug);
ALTER TABLE public.invitations ADD CONSTRAINT invitations_token_key UNIQUE (token);
ALTER TABLE public.organizations ADD CONSTRAINT organizations_slug_key UNIQUE (slug);
ALTER TABLE public.payment_intents ADD CONSTRAINT payment_intents_method_check CHECK ((method = ANY (ARRAY['spei'::text, 'card'::text])));
ALTER TABLE public.payment_intents ADD CONSTRAINT payment_intents_status_check CHECK ((status = ANY (ARRAY['requires_payment'::text, 'processing'::text, 'succeeded'::text, 'failed'::text, 'cancelled'::text, 'expired'::text])));
ALTER TABLE public.payouts ADD CONSTRAINT payouts_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'paid'::text, 'failed'::text, 'reversed'::text])));
ALTER TABLE public.platform_roles ADD CONSTRAINT platform_roles_user_id_role_key UNIQUE (user_id, role);
ALTER TABLE public.pld_questionnaires ADD CONSTRAINT pld_questionnaires_org_id_version_key UNIQUE (org_id, version);
ALTER TABLE public.pld_risk_profiles ADD CONSTRAINT pld_risk_profiles_org_id_key UNIQUE (org_id);
ALTER TABLE public.pld_risk_profiles ADD CONSTRAINT pld_risk_profiles_score_check CHECK (((score >= 0) AND (score <= 100)));
ALTER TABLE public.pld_screening_results ADD CONSTRAINT pld_screening_results_subject_type_check CHECK ((subject_type = ANY (ARRAY['titular'::text, 'representante'::text, 'beneficiario_final'::text, 'contraparte'::text, 'empresa'::text])));
ALTER TABLE public.profiles ADD CONSTRAINT profiles_curp_key UNIQUE (curp);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_mfa_status_check CHECK ((mfa_status = ANY (ARRAY['not_configured'::text, 'pending'::text, 'enabled'::text])));
ALTER TABLE public.reports_ledger ADD CONSTRAINT reports_ledger_kind_check CHECK ((kind = ANY (ARRAY['tx_csv'::text, 'tx_pdf'::text, 'cfdi_stub'::text])));
ALTER TABLE public.stripe_webhook_events ADD CONSTRAINT stripe_webhook_events_event_id_key UNIQUE (event_id);
ALTER TABLE public.support_attachment_downloads ADD CONSTRAINT support_attachment_downloads_user_kind_check CHECK ((user_kind = ANY (ARRAY['user'::text, 'internal'::text])));
ALTER TABLE public.support_tickets ADD CONSTRAINT support_tickets_numero_key UNIQUE (numero);
ALTER TABLE public.transaction_contracts ADD CONSTRAINT transaction_contracts_buyer_signature_method_check CHECK ((buyer_signature_method = ANY (ARRAY['AUTOGRAFA_BIOMETRICA'::text, 'EFIRMA_SAT'::text])));
ALTER TABLE public.transaction_contracts ADD CONSTRAINT transaction_contracts_seller_signature_method_check CHECK ((seller_signature_method = ANY (ARRAY['AUTOGRAFA_BIOMETRICA'::text, 'EFIRMA_SAT'::text])));
ALTER TABLE public.transaction_contracts ADD CONSTRAINT transaction_contracts_signature_order_check CHECK ((signature_order = ANY (ARRAY['PARALLEL'::text, 'SEQUENTIAL'::text])));
ALTER TABLE public.transaction_contracts ADD CONSTRAINT transaction_contracts_source_type_check CHECK ((source_type = ANY (ARRAY['UPLOADED_PDF'::text, 'GENERATED'::text])));
ALTER TABLE public.transaction_contracts ADD CONSTRAINT transaction_contracts_status_check CHECK ((status = ANY (ARRAY['DRAFT'::text, 'READY_TO_SIGN'::text, 'WAITING_BUYER'::text, 'WAITING_SELLER'::text, 'PARTIALLY_SIGNED'::text, 'FULLY_SIGNED'::text, 'REJECTED'::text, 'EXPIRED'::text, 'VOIDED'::text])));
ALTER TABLE public.transaction_documents ADD CONSTRAINT transaction_documents_doc_type_check CHECK ((doc_type = ANY (ARRAY['CONTRATO'::text, 'CFDI'::text, 'COMPROBANTE_PAGO'::text, 'GARANTIA'::text, 'ACTA_ENTREGA'::text, 'OTRO'::text])));
ALTER TABLE public.transaction_documents ADD CONSTRAINT transaction_documents_sat_status_check CHECK ((sat_status = ANY (ARRAY['valid'::text, 'invalid'::text, 'cancelled'::text, 'not_verified'::text, 'error'::text])));
ALTER TABLE public.transaction_hitos ADD CONSTRAINT transaction_hitos_estado_check CHECK ((estado = ANY (ARRAY['PENDIENTE'::text, 'EN_CURSO'::text, 'EN_REVISION'::text, 'APROBADO'::text, 'RECHAZADO'::text, 'CANCELADO'::text])));
ALTER TABLE public.transaction_hitos ADD CONSTRAINT transaction_hitos_monto_porcentaje_check CHECK (((monto_porcentaje >= (0)::numeric) AND (monto_porcentaje <= (100)::numeric)));
ALTER TABLE public.transaction_hitos ADD CONSTRAINT transaction_hitos_responsable_check CHECK ((responsable = ANY (ARRAY['PAGADOR'::text, 'BENEFICIARIO'::text])));
ALTER TABLE public.transaction_hitos ADD CONSTRAINT transaction_hitos_tipo_verificacion_check CHECK ((tipo_verificacion = ANY (ARRAY['DOCUMENTAL'::text, 'EVIDENCIA_FISICA'::text, 'GPS'::text, 'CHECKLIST'::text, 'AUTOMATICO'::text, 'MANUAL_YOKTO'::text])));
ALTER TABLE public.transaction_hitos ADD CONSTRAINT transaction_hitos_transaction_id_orden_key UNIQUE (transaction_id, orden);
ALTER TABLE public.transactions ADD CONSTRAINT transactions_amount_cents_check CHECK ((amount_cents > 0));
ALTER TABLE public.transactions ADD CONSTRAINT transactions_check CHECK (((seller_id IS NOT NULL) OR (counterparty_email IS NOT NULL)));
ALTER TABLE public.transactions ADD CONSTRAINT transactions_commission_bps_check CHECK (((commission_bps >= 0) AND (commission_bps <= 10000)));
ALTER TABLE public.transactions ADD CONSTRAINT transactions_numero_key UNIQUE (numero);
ALTER TABLE public.transactions ADD CONSTRAINT transactions_sector_check CHECK (((sector IS NULL) OR (sector = ANY (ARRAY['AUTOTRANSPORTE'::text, 'CONSTRUCCION'::text, 'COMERCIO_EXTERIOR'::text, 'INMOBILIARIO'::text, 'VEHICULOS'::text, 'SERVICIOS'::text]))));
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_role_key UNIQUE (user_id, role);
ALTER TABLE public.verification_evidence ADD CONSTRAINT verification_evidence_ai_verdict_check CHECK ((ai_verdict = ANY (ARRAY['approve'::text, 'review'::text, 'reject'::text])));
