/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedDisputesRouteImport } from './routes/_authenticated/disputes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTransactionsNewRouteImport } from './routes/_authenticated/transactions.new'
import { Route as AuthenticatedTransactionsIdRouteImport } from './routes/_authenticated/transactions.$id'
import { Route as AuthenticatedDisputesIdRouteImport } from './routes/_authenticated/disputes.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisputesRoute = AuthenticatedDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsNewRoute =
  AuthenticatedTransactionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedTransactionsIdRoute =
  AuthenticatedTransactionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedDisputesIdRoute = AuthenticatedDisputesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDisputesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disputes': typeof AuthenticatedDisputesRouteWithChildren
  '/kyc': typeof AuthenticatedKycRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/disputes/$id': typeof AuthenticatedDisputesIdRoute
  '/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/transactions/new': typeof AuthenticatedTransactionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disputes': typeof AuthenticatedDisputesRouteWithChildren
  '/kyc': typeof AuthenticatedKycRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/disputes/$id': typeof AuthenticatedDisputesIdRoute
  '/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/transactions/new': typeof AuthenticatedTransactionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/disputes': typeof AuthenticatedDisputesRouteWithChildren
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/_authenticated/disputes/$id': typeof AuthenticatedDisputesIdRoute
  '/_authenticated/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/_authenticated/transactions/new': typeof AuthenticatedTransactionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/disputes'
    | '/kyc'
    | '/payments'
    | '/transactions'
    | '/disputes/$id'
    | '/transactions/$id'
    | '/transactions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/disputes'
    | '/kyc'
    | '/payments'
    | '/transactions'
    | '/disputes/$id'
    | '/transactions/$id'
    | '/transactions/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/disputes'
    | '/_authenticated/kyc'
    | '/_authenticated/payments'
    | '/_authenticated/transactions'
    | '/_authenticated/disputes/$id'
    | '/_authenticated/transactions/$id'
    | '/_authenticated/transactions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disputes': {
      id: '/_authenticated/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof AuthenticatedDisputesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/new': {
      id: '/_authenticated/transactions/new'
      path: '/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof AuthenticatedTransactionsNewRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/transactions/$id': {
      id: '/_authenticated/transactions/$id'
      path: '/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof AuthenticatedTransactionsIdRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/disputes/$id': {
      id: '/_authenticated/disputes/$id'
      path: '/$id'
      fullPath: '/disputes/$id'
      preLoaderRoute: typeof AuthenticatedDisputesIdRouteImport
      parentRoute: typeof AuthenticatedDisputesRoute
    }
  }
}

interface AuthenticatedDisputesRouteChildren {
  AuthenticatedDisputesIdRoute: typeof AuthenticatedDisputesIdRoute
}

const AuthenticatedDisputesRouteChildren: AuthenticatedDisputesRouteChildren = {
  AuthenticatedDisputesIdRoute: AuthenticatedDisputesIdRoute,
}

const AuthenticatedDisputesRouteWithChildren =
  AuthenticatedDisputesRoute._addFileChildren(
    AuthenticatedDisputesRouteChildren,
  )

interface AuthenticatedTransactionsRouteChildren {
  AuthenticatedTransactionsIdRoute: typeof AuthenticatedTransactionsIdRoute
  AuthenticatedTransactionsNewRoute: typeof AuthenticatedTransactionsNewRoute
}

const AuthenticatedTransactionsRouteChildren: AuthenticatedTransactionsRouteChildren =
  {
    AuthenticatedTransactionsIdRoute: AuthenticatedTransactionsIdRoute,
    AuthenticatedTransactionsNewRoute: AuthenticatedTransactionsNewRoute,
  }

const AuthenticatedTransactionsRouteWithChildren =
  AuthenticatedTransactionsRoute._addFileChildren(
    AuthenticatedTransactionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDisputesRoute: typeof AuthenticatedDisputesRouteWithChildren
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDisputesRoute: AuthenticatedDisputesRouteWithChildren,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
