/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedDisputesRouteImport } from './routes/_authenticated/disputes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApiClientsRouteImport } from './routes/_authenticated/api-clients'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTransactionsNewRouteImport } from './routes/_authenticated/transactions.new'
import { Route as AuthenticatedTransactionsIdRouteImport } from './routes/_authenticated/transactions.$id'
import { Route as AuthenticatedOnboardingPendienteRouteImport } from './routes/_authenticated/onboarding.pendiente'
import { Route as AuthenticatedDisputesIdRouteImport } from './routes/_authenticated/disputes.$id'
import { Route as ApiPublicV1TransactionsRouteImport } from './routes/api/public/v1.transactions'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisputesRoute = AuthenticatedDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiClientsRoute = AuthenticatedApiClientsRouteImport.update({
  id: '/api-clients',
  path: '/api-clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsNewRoute =
  AuthenticatedTransactionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedTransactionsIdRoute =
  AuthenticatedTransactionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedOnboardingPendienteRoute =
  AuthenticatedOnboardingPendienteRouteImport.update({
    id: '/onboarding/pendiente',
    path: '/onboarding/pendiente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDisputesIdRoute = AuthenticatedDisputesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDisputesRoute,
} as any)
const ApiPublicV1TransactionsRoute = ApiPublicV1TransactionsRouteImport.update({
  id: '/api/public/v1/transactions',
  path: '/api/public/v1/transactions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api-clients': typeof AuthenticatedApiClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disputes': typeof AuthenticatedDisputesRouteWithChildren
  '/kyc': typeof AuthenticatedKycRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/disputes/$id': typeof AuthenticatedDisputesIdRoute
  '/onboarding/pendiente': typeof AuthenticatedOnboardingPendienteRoute
  '/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/transactions/new': typeof AuthenticatedTransactionsNewRoute
  '/api/public/v1/transactions': typeof ApiPublicV1TransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api-clients': typeof AuthenticatedApiClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disputes': typeof AuthenticatedDisputesRouteWithChildren
  '/kyc': typeof AuthenticatedKycRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/disputes/$id': typeof AuthenticatedDisputesIdRoute
  '/onboarding/pendiente': typeof AuthenticatedOnboardingPendienteRoute
  '/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/transactions/new': typeof AuthenticatedTransactionsNewRoute
  '/api/public/v1/transactions': typeof ApiPublicV1TransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/api-clients': typeof AuthenticatedApiClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/disputes': typeof AuthenticatedDisputesRouteWithChildren
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/_authenticated/disputes/$id': typeof AuthenticatedDisputesIdRoute
  '/_authenticated/onboarding/pendiente': typeof AuthenticatedOnboardingPendienteRoute
  '/_authenticated/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/_authenticated/transactions/new': typeof AuthenticatedTransactionsNewRoute
  '/api/public/v1/transactions': typeof ApiPublicV1TransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/sitemap.xml'
    | '/admin'
    | '/api-clients'
    | '/dashboard'
    | '/disputes'
    | '/kyc'
    | '/payments'
    | '/reports'
    | '/transactions'
    | '/disputes/$id'
    | '/onboarding/pendiente'
    | '/transactions/$id'
    | '/transactions/new'
    | '/api/public/v1/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/sitemap.xml'
    | '/admin'
    | '/api-clients'
    | '/dashboard'
    | '/disputes'
    | '/kyc'
    | '/payments'
    | '/reports'
    | '/transactions'
    | '/disputes/$id'
    | '/onboarding/pendiente'
    | '/transactions/$id'
    | '/transactions/new'
    | '/api/public/v1/transactions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/api-clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/disputes'
    | '/_authenticated/kyc'
    | '/_authenticated/payments'
    | '/_authenticated/reports'
    | '/_authenticated/transactions'
    | '/_authenticated/disputes/$id'
    | '/_authenticated/onboarding/pendiente'
    | '/_authenticated/transactions/$id'
    | '/_authenticated/transactions/new'
    | '/api/public/v1/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicV1TransactionsRoute: typeof ApiPublicV1TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disputes': {
      id: '/_authenticated/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof AuthenticatedDisputesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-clients': {
      id: '/_authenticated/api-clients'
      path: '/api-clients'
      fullPath: '/api-clients'
      preLoaderRoute: typeof AuthenticatedApiClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/new': {
      id: '/_authenticated/transactions/new'
      path: '/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof AuthenticatedTransactionsNewRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/transactions/$id': {
      id: '/_authenticated/transactions/$id'
      path: '/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof AuthenticatedTransactionsIdRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/onboarding/pendiente': {
      id: '/_authenticated/onboarding/pendiente'
      path: '/onboarding/pendiente'
      fullPath: '/onboarding/pendiente'
      preLoaderRoute: typeof AuthenticatedOnboardingPendienteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disputes/$id': {
      id: '/_authenticated/disputes/$id'
      path: '/$id'
      fullPath: '/disputes/$id'
      preLoaderRoute: typeof AuthenticatedDisputesIdRouteImport
      parentRoute: typeof AuthenticatedDisputesRoute
    }
    '/api/public/v1/transactions': {
      id: '/api/public/v1/transactions'
      path: '/api/public/v1/transactions'
      fullPath: '/api/public/v1/transactions'
      preLoaderRoute: typeof ApiPublicV1TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDisputesRouteChildren {
  AuthenticatedDisputesIdRoute: typeof AuthenticatedDisputesIdRoute
}

const AuthenticatedDisputesRouteChildren: AuthenticatedDisputesRouteChildren = {
  AuthenticatedDisputesIdRoute: AuthenticatedDisputesIdRoute,
}

const AuthenticatedDisputesRouteWithChildren =
  AuthenticatedDisputesRoute._addFileChildren(
    AuthenticatedDisputesRouteChildren,
  )

interface AuthenticatedTransactionsRouteChildren {
  AuthenticatedTransactionsIdRoute: typeof AuthenticatedTransactionsIdRoute
  AuthenticatedTransactionsNewRoute: typeof AuthenticatedTransactionsNewRoute
}

const AuthenticatedTransactionsRouteChildren: AuthenticatedTransactionsRouteChildren =
  {
    AuthenticatedTransactionsIdRoute: AuthenticatedTransactionsIdRoute,
    AuthenticatedTransactionsNewRoute: AuthenticatedTransactionsNewRoute,
  }

const AuthenticatedTransactionsRouteWithChildren =
  AuthenticatedTransactionsRoute._addFileChildren(
    AuthenticatedTransactionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedApiClientsRoute: typeof AuthenticatedApiClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDisputesRoute: typeof AuthenticatedDisputesRouteWithChildren
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRouteWithChildren
  AuthenticatedOnboardingPendienteRoute: typeof AuthenticatedOnboardingPendienteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedApiClientsRoute: AuthenticatedApiClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDisputesRoute: AuthenticatedDisputesRouteWithChildren,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRouteWithChildren,
  AuthenticatedOnboardingPendienteRoute: AuthenticatedOnboardingPendienteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicV1TransactionsRoute: ApiPublicV1TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
